services:
  jupyter-lab:
    container_name: electricity-demand-jupyter
    build: ./app
    volumes:
      - ./app:/app
    ports:
      - 8888:8888
    command: >
      jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token=''
